name: research_package
description: A Flutter framework for obtaining informed consent, showing surveys and collecting results.
version: 0.4.0
homepage: https://github.com/cph-cachet/research.package

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  signature: ^4.0.0-nullsafety
  rxdart: ^0.26.0
  json_annotation: ^4.0.0
  flutter_localizations:
    sdk: flutter
  collection: ^1.15.0
  simple_html_css: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
#  test: ^1.14.3

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icons/
    - assets/icons/analysis.png
    - assets/icons/archive.png
    - assets/icons/deadline.png
    - assets/icons/document.png
    - assets/icons/handshake.png
    - assets/icons/id.png
    - assets/icons/management.png
    - assets/icons/networking.png
    - assets/icons/settings.png
    - assets/icons/target.png
    - assets/icons/id.png
