name: research_package
description: A Flutter framework for obtaining informed consent, showing surveys and collecting results.
version: 0.7.2+3
homepage: https://github.com/cph-cachet/research.package

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_core: ^0.31.0 # the core CARP domain model

  signature: ^5.0.0
  rxdart: ^0.27.1
  json_annotation: ^4.3.0
  simple_html_css: ^3.0.1
  collection: ^1.15.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

  test: ^1.17.9

flutter:
  assets:
    - assets/icons/analysis.png
    - assets/icons/archive.png
    - assets/icons/checkmark.png
    - assets/icons/deadline.png
    - assets/icons/document.png
    - assets/icons/handshake.png
    - assets/icons/health.png
    - assets/icons/id.png
    - assets/icons/location.png
    - assets/icons/management.png
    - assets/icons/networking.png
    - assets/icons/settings.png
    - assets/icons/target.png
    - assets/icons/task.png
    - assets/lang/
