name: research_package
description: A Flutter framework for obtaining informed consent, showing surveys and collecting results.
version: 1.3.0
homepage: https://github.com/cph-cachet/research.package

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.1.0

  signature: ^5.3.0
  rxdart: ^0.27.7
  json_annotation: ^4.7.0
  simple_html_css: ^4.0.0
  audiofileplayer: ^2.1.1

# Overriding carp core libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_serializable:
  #   path: ../carp/carp.sensing-flutter/carp_serializable/


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any
  flutter_lints: any
  test: any

flutter:
  assets:
    - assets/icons/analysis.png
    - assets/icons/archive.png
    - assets/icons/checkmark.png
    - assets/icons/deadline.png
    - assets/icons/document.png
    - assets/icons/handshake.png
    - assets/icons/health.png
    - assets/icons/id.png
    - assets/icons/location.png
    - assets/icons/management.png
    - assets/icons/networking.png
    - assets/icons/settings.png
    - assets/icons/target.png
    - assets/icons/task.png
    - assets/lang/
    - assets/audio/RPTimerStepSound.mp3
